spring:
  profiles:
    active: dev


mabatis:
  mapper-locations:
    - classpath:cn.threo.imitationmall.dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization
  secret: mySecret
  expiration: 604800 #1day 60*60*24
  tokenHead: Bearer

logging:
  level:
    root: info
    cn.threo.imitationmall: debug
